server:
  port: 9001
spring:
  application:
    name: openeuler-base #指定服务名
jwt:
  config:
    key: itcast
    ttl: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    user:
      path: /user/**
      service-id: openeuler-user
      strip-prefix: false
    storage:
      path: /maven/**
      service-id: openeuler-storage
      strip-prefix: false
    share:
      path: /share/**
      service-id: openeuler-share
      strip-prefix: false
