server:
  port: ${PORT:9001}
spring:
  application:
    name: openeuler-base #指定服务名
jwt:
  config:
    key: ${JWT_KEY:openeuler}
    ttl: 86400000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKASERVER_URI:http://localhost:6868/eureka/}
  instance:
    prefer-ip-address: true

zuul:
  routes:
    user:
      path: /user/**
      service-id: openeuler-user
      strip-prefix: false
    storage:
      path: /maven/**
      service-id: openeuler-storage
      strip-prefix: false
    share:
      path: /share/**
      service-id: openeuler-share
      strip-prefix: false
    web:
      path: /**
      url: ${FRONTEND_URI:http://localhost:9528/}
ribbon:
  ReadTimeout: 60000