component: koa
name: koaDemo
app: openeuler-repo
inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-beijing
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
