server:
  port: ${PORT:9008}
spring:
  application:
    name: openeuler-user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${DB_BASE_NAME:openeuler}_user?characterEncoding=utf-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: ${JWT_KEY:openeuler}
    ttl: 86400000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKASERVER_URI:http://localhost:6868/eureka/}
  instance:
    prefer-ip-address: true
amazon:
  s3:
    url: ${S3_MAVEN_URL}