server:
  port: ${PORT:9009}
spring:
  application:
    name: openeuler-storage #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${DB_BASE_NAME:openeuler}_storage?characterEncoding=utf-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
amazon:
  s3:
    bucket-name: ${S3_BUCKET}
    region: ${S3_REGION}
    endpoint: ${S3_ENDPOINT}
    url: ${S3_URL}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKASERVER_URI:http://localhost:6868/eureka/}
  instance:
    prefer-ip-address: true
